apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    service: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
      - name: mongodb
        image: robotshop/rs-mongodb:latest
        # imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        livenessProbe:
          periodSeconds: 5
          httpGet:
            path: /health
            port: 27017
      restartPolicy: Always
