apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment
      stage: prod
  template:
    metadata:
      labels:
        service: payment
        stage: prod
    spec:
      containers:
      - name: payment
        image: robotshop/rs-payment:latest
        # imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef: 
                fieldPath: status.hostIP 
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        livenessProbe:
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
      restartPolicy: Always
