apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    service: user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user
  template:
    metadata:
      labels:
        service: user
    spec:
      containers:
      - name: user
        image: robotshop/rs-user:latest
        # imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef: 
                fieldPath: status.hostIP 
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        # livenessProbe:
        #   periodSeconds: 5
        #   httpGet:
        #     path: /health
        #     port: 8080
      restartPolicy: Always
