apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    service: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: web
        image: robotshop/rs-web:latest
        # imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        # livenessProbe:
        #   periodSeconds: 5
        #   httpGet:
        #     path: /health
        #     port: 8080
      restartPolicy: Always
